let selectedImage = "";


// Image Preview

document.getElementById("imageInput").addEventListener("change", function(){

    let file = this.files[0];

    if(file){

        selectedImage = file.name;

        let reader = new FileReader();


        reader.onload = function(e){

            let img = document.getElementById("previewImage");

            img.src = e.target.result;

            img.style.display="block";

        }


        reader.readAsDataURL(file);

    }

});




// Disease Database


const diseaseData = {


Tomato:{

disease:"Tomato Early Blight",

confidence:"92%",

medicine:"Use Mancozeb 75 WP or Copper Oxychloride spray. Apply as recommended by agriculture expert.",

tips:"Remove infected leaves, maintain proper spacing, avoid excess water on leaves."

},



Potato:{

disease:"Potato Late Blight",

confidence:"90%",

medicine:"Spray Metalaxyl + Mancozeb fungicide.",

tips:"Use disease free seeds and avoid water logging."

},



Onion:{

disease:"Onion Purple Blotch",

confidence:"88%",

medicine:"Apply Mancozeb or Chlorothalonil fungicide.",

tips:"Keep field clean and maintain proper irrigation."

},



Rice:{

disease:"Rice Blast Disease",

confidence:"91%",

medicine:"Use Tricyclazole fungicide spray.",

tips:"Avoid excess nitrogen fertilizer and maintain field hygiene."

},



Wheat:{

disease:"Wheat Rust",

confidence:"89%",

medicine:"Apply Propiconazole fungicide.",

tips:"Grow resistant varieties and remove infected plants."

},



Cotton:{

disease:"Cotton Leaf Curl Virus",

confidence:"87%",

medicine:"Control whitefly using recommended pesticides.",

tips:"Remove infected plants and maintain crop monitoring."

},



Soybean:{

disease:"Soybean Rust",

confidence:"86%",

medicine:"Use suitable fungicide spray after expert advice.",

tips:"Maintain crop spacing and remove infected leaves."

},



Chilli:{

disease:"Chilli Leaf Curl Disease",

confidence:"90%",

medicine:"Control aphids and whiteflies using recommended insecticide.",

tips:"Use healthy seedlings and remove affected plants."

},



Banana:{

disease:"Panama Disease",

confidence:"85%",

medicine:"Use disease management practices recommended for banana crop.",

tips:"Maintain soil health and remove infected plants."

},



Mango:{

disease:"Mango Powdery Mildew",

confidence:"88%",

medicine:"Apply Sulphur based fungicide.",

tips:"Provide proper air circulation between plants."

},



Grapes:{

disease:"Grape Downy Mildew",

confidence:"89%",

medicine:"Use approved fungicide spray.",

tips:"Avoid excess moisture and maintain vineyard hygiene."

},



Papaya:{

disease:"Papaya Ring Spot Virus",

confidence:"86%",

medicine:"Control insect vectors and remove infected plants.",

tips:"Use healthy planting material."

}


};






// Disease Detection Function


function detectDisease(){



let crop = document.getElementById("crop").value;



if(crop===""){

alert("Please select crop first");

return;

}



let data = diseaseData[crop];



document.getElementById("result").style.display="block";



document.getElementById("diseaseName").innerHTML =
"🌿 "+data.disease;


document.getElementById("resultCrop").innerHTML =
crop;


document.getElementById("confidence").innerHTML =
data.confidence;



document.getElementById("medicine").innerHTML =
data.medicine;



document.getElementById("tips").innerHTML =
data.tips;



}




// PDF Report Download


function downloadReport(){


let crop =
document.getElementById("resultCrop").innerText;


let disease =
document.getElementById("diseaseName").innerText;


let medicine =
document.getElementById("medicine").innerText;


let tips =
document.getElementById("tips").innerText;



let report =

`
AgriConnect Crop Disease Report

Crop:
${crop}


Disease:
${disease}


Medicine Recommendation:

${medicine}


Prevention Tips:

${tips}



Generated by AgriConnect Smart Farmer Assistant
`;



let blob = new Blob([report],{

type:"text/plain"

});



let link=document.createElement("a");


link.href=URL.createObjectURL(blob);


link.download="Crop_Disease_Report.txt";


link.click();


}